steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['jib', '--image' ,'gcr.io/rocket-dev01/push-service-worker']

- name: gcr.io/cloud-builders/gcloud
  args: ['run', 'deploy', 'push-service-worker', '--image', 'gcr.io/rocket-dev01/push-service-worker', '--platform', 'managed', '--region', 'us-central1', '--memory', '512M', '--cpu', '2', '--concurrency', '80', '--no-allow-unauthenticated']
